framework:
    default_locale: 'en'
    translator:
        default_path: '%kernel.project_dir%/config/packages'
        fallbacks:
            - 'en'

'Your password must be at least {{ limit }} characters long.': 'Your password must be at least 8 characters long.'
